version: "3"

services:
  auth-api:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: lfo/nodejs
    ports: 
      - "9090"
    networs:
      - dev-network

networks:
  dev-network:
    driver: bridge